# Generated by Django 5.1.2 on 2024-10-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_role_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="supplier",
        ),
    ]
