# Generated by Django 5.1.2 on 2024-10-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                ("model", models.CharField(max_length=255, verbose_name="model")),
                ("release_date", models.DateField(verbose_name="release date")),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "role_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="electronics.role",
                    ),
                ),
            ],
            bases=("electronics.role",),
        ),
        migrations.CreateModel(
            name="IndividualEntrepreneur",
            fields=[
                (
                    "role_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="electronics.role",
                    ),
                ),
            ],
            bases=("electronics.role",),
        ),
        migrations.CreateModel(
            name="RetailChain",
            fields=[
                (
                    "role_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="electronics.role",
                    ),
                ),
            ],
            bases=("electronics.role",),
        ),
        migrations.AddField(
            model_name="role",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="electronics.product", verbose_name="products"
            ),
        ),
    ]
