# Generated by Django 5.1.2 on 2024-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0004_alter_role_role_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Factory", "Factory"),
                    ("RetailChain", "Retail Chain"),
                    ("IndividualEntrepreneur", "Individual Entrepreneur"),
                    ("Employee", "Employee"),
                ],
                max_length=30,
                verbose_name="role type",
            ),
        ),
    ]
