# Generated by Django 5.1.2 on 2024-10-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0005_alter_role_role_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("factory", "Factory"),
                    ("retailchain", "Retail Chain"),
                    ("individualentrepreneur", "Individual Entrepreneur"),
                    ("employee", "Employee"),
                ],
                max_length=30,
                verbose_name="role type",
            ),
        ),
    ]
